name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop  # or your branch of choice
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'  # Enables caching of npm dependencies

      - name: Install dependencies
        run: npm ci
        
      - name: Check for build errors
        run: npm run lint --if-present
        
      - name: Build the app
        run: npm run build
        env:
          CI: true
          # Add any environment variables needed for build
          # VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: 'Deploy to GitHub Pages'
          # Enable if you want to keep deployment history
          keep_files: false
          # Enable if you want to add a custom domain
          # cname: your-custom-domain.com